#!/bin/sh

awk '
{
    name[$2] = $3
    adj[$1, ++n[$1]] = $2
}
END {
    ban["mpif.h"]
    for (s in n)
	if (s ~ /\.f90$/)
	    dfs(s)
}

function dfs(s,   q, i, j, k, seen, nxt, c) {
    q[++j] = s
    while (++i in q) {
	seen[c = q[i]]
	for (k = 1; (c, k) in adj; k++) {
	    nxt = adj[c, k]
	    if (!(nxt in seen)) {
		q[++j] = nxt
		if (!(nxt in ban))
		    print f2obj(s) " : " name[nxt]
	    }
	}
    }
}

function f2obj(s) {
    sub(/\.f90$/, ".o", s)
    return s
}

' | sort | uniq
