#!/bin/sh

awk '
sub(/^[ \t]*INCLUDE[ \t]/, "") && gsub(/'\''/, "") {
    if (!/^fftw3\.f03$/)
	print FILENAME, $0, $0
}
sub(/^[ \t]*#[ \t]*include[ \t]*"/, "") && sub(/".*/, "") {
    print FILENAME, $0, $0
}
sub(/^[ \t]*USE[ \t]+/, "") {
    sub(/!.*$/, "")
    sub(/,.*/, "")
    sub(/[ \t]*$/, "")
    if ( (!/^ppm_module/ || /^ppm_module_fft$/) && !/^MPI$/ && !/^netcdf$/)
	print FILENAME, $0 ".f90", $0 ".o"
 }
' "$@" | sort | uniq
