#!/bin/sh

awk '
sub(/^[ \t]*include[ \t]+"/, "") && sub(/".*/, "") {
    print FILENAME, $0, $0
}
sub(/^[ \t]*INCLUDE[ \t]/, "") && gsub(/'\''/, "") {
    print FILENAME, $0, $0
}
sub(/^[ \t]*USE[ \t]+/, "") {
    sub(/!.*$/, "")
    sub(/,.*/, "")
    sub(/[ \t]*$/, "")
    $0 = tolower($0)
    if (!/^iso_/)
	print FILENAME, $0 ".f90", $0 ".o"
 }
' "$@" | sort | uniq
