module_netcdf4_f03.o : module_netcdf4_nf_interfaces.o
module_netcdf4_f03.o : module_netcdf_nf_data.o
module_netcdf4_f03.o : module_netcdf_nf_interfaces.o
module_netcdf4_nc_interfaces.o : module_netcdf_nc_interfaces.o
module_netcdf4_nf_interfaces.o : module_netcdf4_nc_interfaces.o
module_netcdf4_nf_interfaces.o : module_netcdf_nf_data.o
module_netcdf_f03.o : module_netcdf_nf_data.o
module_netcdf_f03.o : module_netcdf_nf_interfaces.o
module_netcdf_fortv2_c_interfaces.o : module_netcdf_nc_interfaces.o
module_netcdf_nc_interfaces.o : module_netcdf_nc_data.o
module_netcdf_nf_data.o : module_netcdf_nc_data.o
module_netcdf_nf_interfaces.o : module_netcdf_nf_data.o
netcdf4.o : netcdf4_eightbyte.inc
netcdf4.o : netcdf4_externals.inc
netcdf4.o : netcdf4_file.inc
netcdf4.o : netcdf4_func.inc
netcdf4.o : netcdf4_overloads.inc
netcdf4.o : netcdf4_variables.inc
netcdf4.o : netcdf4_visibility.inc
netcdf4.o : netcdf_attributes.inc
netcdf4.o : netcdf_constants.inc
netcdf4.o : netcdf_dims.inc
netcdf4.o : netcdf_expanded.inc
netcdf4.o : netcdf_externals.inc
netcdf4.o : netcdf_file.inc
netcdf4.o : netcdf_overloads.inc
netcdf4.o : netcdf_text_variables.inc
netcdf4.o : netcdf_visibility.inc
netcdf4.o : typesizes.o
