ppm_module_fft.o : ppm_fft_diagnostics.inc
ppm_module_fft.o : ppm_fft_killdiv.inc
ppm_module_fft.o : ppm_fft_velocities_bgw.inc
ppm_module_fft.o : ppm_fft_velocities.inc
rootfinders.o : module_wvic.o
sisec.o : module_wvic.o
wvic_alloc_field.o : module_wvic.o
wvic_barycentric.o : module_wvic.o
wvic_check_abort.o : module_wvic.o
wvic_compvel.o : module_wvic.o
wvic_dgammadt.o : module_wvic.o
wvic_dgammadt_wall.o : module_wvic.o
wvic_diagnostics.o : module_wvic.o
wvic_died.o : module_wvic.o
wvic_dumpfield_plot3d.o : module_wvic.o
wvic_dump_restart.o : module_wvic.o
wvic_enforcetv0.o : module_wvic.o
wvic_enforcetv1.o : module_wvic.o
wvic_enforcetv2.o : module_wvic.o
wvic_enforcewall.o : module_wvic.o
wvic_field2netcdf.o : module_wvic.o
wvic_forcenoca.o : module_wvic.o
wvic_ghost.o : module_wvic.o
wvic_init_cart.o : module_wvic.o
wvic_init_helphysics_0.o : module_wvic.o
wvic_init_helphysics_0.o : ppm_module_fft.o
wvic_init_physics_0.o : module_wvic.o
wvic_init_physics_4.o : module_wvic.o
wvic_init_physics_4.o : ppm_module_fft.o
wvic_init_physics_4.o : wvic_put_a_ring.inc
wvic_init_physics_5.o : module_wvic.o
wvic_init_physics_5.o : ppm_module_fft.o
wvic_init_physics_5.o : wvic_put_a_ring.inc
wvic_init_physics_6.o : module_wvic.o
wvic_init_physics_6.o : ppm_module_fft.o
wvic_init_stdobjs.o : module_wvic.o
wvic_init_stdobjs.o : ppm_module_fft.o
wvic_init_tvphysics_0.o : module_wvic.o
wvic_init_tvphysics_0.o : ppm_module_fft.o
wvic_init_tvphysics_1.o : module_wvic.o
wvic_init_tvphysics_2.o : module_wvic.o
wvic_init_tvphysics_2.o : ppm_module_fft.o
wvic_iswall.o : module_wvic.o
wvic_les_hypervisc.o : module_wvic.o
wvic_les_tdmclipped.o : module_wvic.o
wvic_map_particles.o : module_wvic.o
wvic_medusa.o : module_wvic.o
wvic_medusa.o : ppm_module_fft.o
wvic_module_io.o : module_wvic.o
wvic_module_io.o : wvic_io_dump_scalar_netcdf.inc
wvic_module_io.o : wvic_io_dump_scalar_vtk.inc
wvic_module_io.o : wvic_io_dump_vector_netcdf.inc
wvic_module_io.o : wvic_io_dump_vector_vtk.inc
wvic_movement.o : module_wvic.o
wvic_netcdf2field.o : module_wvic.o
wvic.o : module_wvic.o
wvic_pbc.o : module_wvic.o
wvic_penal.o : module_wvic.o
wvic_poisson.o : module_wvic.o
wvic_poisson.o : ppm_module_fft.o
wvic_readparams.o : module_wvic.o
wvic_readstl.o : module_wvic.o
wvic_rhs_loca.o : module_wvic.o
wvic_rhs_vort.o : module_wvic.o
wvic_run.o : module_wvic.o
wvic_stepfunction.o : module_wvic.o
wvic_stepfunction.o : ppm_module_fft.o
wvic_suck_restart.o : module_wvic.o
wvic_tvdrk3.o : module_wvic.o
wvic_tvdrk3.o : ppm_module_fft.o
wvic_tvdrk3.o : wvic_module_io.o
wvic_write_restart.o : module_wvic.o
